name: 'AI Diagnostic - Linting'
description: 'Quality checks with flake8 and pylint'

runs:
  using: composite
  steps:
    - name: Run flake8
      run: uv run flake8 app/ tests/
      shell: bash
      continue-on-error: true
    
    - name: Run pylint
      run: uv run pylint app/ || true
      shell: bash
      continue-on-error: true
