"""
File: app/agents/diagnostician.py
Description: AI Agent that generates actionable fix suggestions for PLC errors
using deterministic metadata and XML context. [cite: 39]
"""

# Standard Library Imports
import os
from typing import Any, Dict

from loguru import logger

# Third-Party Imports
from openai import OpenAI

# Internal Imports
from app.agents.schemas import DiagnosticReport


class PLCDiagnosticAgent:
    """
    Expert AI Agent specializing in IEC 61131-3 and industrial automation. [cite: 5, 39]
    """

    def __init__(self):
        """Initializes the OpenAI client using environment variables."""
        self.api_key = os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            logger.error("OPENAI_API_KEY not found in environment.")

        self.client = OpenAI(api_key=self.api_key)
        self.model = "gpt-4o-2024-08-06"  # Model with native structured output support

    def get_fix_suggestions(
        self, metadata: Dict[str, Any], xml_context: str
    ) -> DiagnosticReport:
        """
        Analyzes the error using LLM reasoning and returns a structured report. [cite: 8, 21-24]
        """

        system_prompt = (
            "You are a Lead Automation Engineer. Analyze PLC compilation logs and project XML. "
            "Prioritize the root cause. If it's a 'constant_error', explain that CONSTANT variables "
            "cannot be modified in Structured Text. If it's a code generation crash with no ST code, "
            "explain the POU is empty. [cite: 7, 8, 23]"
        )

        user_prompt = (
            f"Build Stage: {metadata['stage']}\n"
            f"Error Line: {metadata['line']}\n"
            f"XML Context Snippet: \n{xml_context}\n\n"
            "Generate a diagnostic report with 1-3 actionable suggestions. "
        )

        try:
            # Using 'beta.chat.completions.parse' for guaranteed schema adherence
            response = self.client.beta.chat.completions.parse(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format=DiagnosticReport,  # Strictly follows your Pydantic schema
            )

            logger.success("Structured diagnostic generated by AI.")
            return response.choices[0].message.parsed

        except Exception as e:
            logger.error(f"AI Generation failed: {e}")
            raise
