name: 'AI Diagnostic - Setup Python'
description: 'Setup Python environment for AI PLC diagnostic system'

inputs:
  python-version:
    required: false
    default: '3.12'
    description: 'Python version (3.10, 3.11, 3.12)'

runs:
  using: composite
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ inputs.python-version }}"
    
    - name: Upgrade pip and setuptools
      run: python -m pip install --upgrade pip setuptools
      shell: bash
    
    - name: Install uv for package management
      run: pip install uv
      shell: bash
    
    - name: Install project dependencies
      run: |
        uv pip install --system fastapi google-genai google-generativeai loguru lxml openai pydantic-settings pytest-cov pytest-mock python-dotenv uvicorn pytest
      shell: bash
