name: 'Setup Python Environment'
description: 'Setup Python with uv package manager for AI Diagnostic project'

inputs:
  python-version:
    required: false
    default: '3.14'
    description: 'Python version (3.14+)'

runs:
  using: composite
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ inputs.python-version }}"
    
    - name: Upgrade pip and setuptools
      run: python -m pip install --upgrade pip setuptools
      shell: bash
    
    - name: Install uv for package management
      run: pip install uv
      shell: bash
    
    - name: Install project dependencies
      run: uv sync
      shell: bash
